title:            Chunglae Cho
description:      Chunglae Cho's Personal Homepage & Blog
url:              # Site url.
signoff:          # Your name.
disqus_shortname: # disqus comment thread for post header options. ( leave blank if unwanted. )
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name:         About
    url:          /about
  - name:         Publications
    url:          /publications
  - name:         Interests
    url:          /
  - name:         GitHub
    url:          http://github.com/clcho
    external:     true
pygments:         true
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
